add golang generator
jenner/LstGen pull request #23
Opened 2021-10-18 19:22 UTC by polderudo

Hello Igor,
as i am also not very good at python, i created a new generator (golang).
I removed the dependency to github.com/shopspring/decimal and implemented the needed functionality into a small struct.

I'v been running the code through 96000 datasets through the BFM API and at least for 2021 everthings seems to work ok.
Would be cool if you can accept the PR.

2021-11-02 12:52 UTC, jenner commented
Hi Udo, thanks a lot for the code! Would you consider moving the BigDecimal code to an extra file and use it in the genrated code (much like the PHP generator does)?

2021-11-02 12:55 UTC, jenner commented
@knipknap do you think there's a way to merge the code from @polderudo with your Go generator? I'd really like to keep just one generator per language.

2021-11-02 13:36 UTC, polderudo commented
> Hi Udo, thanks a lot for the code! Would you consider moving the BigDecimal code to an extra file and use it in the genrated code (much like the PHP generator does)?

Hi, sure. Will do that this evening

2022-09-06 06:57 UTC, jenner commented
Hi Udo, what is this taxfiles folder for? It doesn't look like it belongs here

2022-09-06 07:02 UTC, polderudo commented
Oh my god. Sorry I did not want to push that... I will fix that in the next few days, vacation...
Also, the 2022 golang generator has some problems with the latest PAP. I had to use the python version for correct values. Will also look for this when I'm back.
Sorry that I pushed that to the PR.

2022-09-08 18:17 UTC, polderudo commented
Hello Igor, i pushed a version with the files removed. But the generator still has a problem. Starting from 2800 € we get a rounding error from one cent. The python version is working correct.
I will have to investigate where the error comes from.

2022-09-09 19:29 UTC, polderudo commented
Hello Igor, i fixed the problem with the rounding in the Divide function. Also the 2022 PAP is in and i also tested it through the BFM API. If you like you could merge the PR as new version with the golang generator. Seems, like we get no response from the go guy.

2022-09-13 11:20 UTC, jenner requested changes

2022-09-13 11:20 UTC, jenner commented on lstgen/cli.py
> +from lstgen.generators import GENERATORS
Any particular reason for this change?

2022-09-13 11:20 UTC, jenner commented on lstgen/cli.py
I don't think this belongs here

2022-09-13 11:20 UTC, jenner commented on setup.py
> +    version='0.5.6',
Please let me change this in an extra commit when I bump the version and update the release note

2022-09-13 11:20 UTC, jenner commented on lstgen/generators/golang/__init__.py
> +        """ Converts java pseudo code into valid java code """
Misleading docstring :)

2022-09-14 17:15 UTC, polderudo commented
Hello Igor, i pushed a new version. Sorry, my python skills are not that good...

2022-09-19 11:15 UTC, merged

2022-09-19 11:18 UTC, jenner commented
Thanks Udo! Do you think we can safely remove the "old" go generator? I think it makes little to no sense to have two of them

2022-09-19 11:20 UTC, polderudo commented
> Thanks Udo! Do you think we can safely remove the "old" go generator? I think it makes little to no sense to have two of them

I think yes. I mean, it did not round correct anyway, so even if my version would have bugs it would not be worse :)