Add support for the 2022 xml based PAP files to generate the german L…
jenner/LstGen pull request #25
Opened 2022-01-11 23:22 UTC by 0xCCD

Support für die Lohnsteuer 2022 files

2022-01-13 13:25 UTC, jenner commented on README.md
> +Das generierte Node Module erfordert eine BigDecimal implementierung.
Implementierung

2022-01-13 13:30 UTC, jenner requested changes
Bitte noch ein Paar kleine Rechtschreibfehler beheben,
Die Version- und Changelog-Anpassungen mache ich gerne selbst in einem extra Commit.

Danke!

2022-01-13 21:10 UTC, 0xCCD commented
> Bitte noch ein Paar kleine Rechtschreibfehler beheben, Die Version- und Changelog-Anpassungen mache ich gerne selbst in einem extra Commit.
> 
> Danke!

Ist erledigt

2022-01-25 08:43 UTC, maxmessing commented
Hi Igor,

magst Du noch mal reviewen?

2022-03-28 08:42 UTC, maxmessing approved these changes

2022-10-17 11:52 UTC, merged